### ISSUE TITLE
If you minds sharing something provide picture, or at least detailed content description

### ISSUE THREAD

**Issue by ardissaps** [JoostMSoftware/EveryRandomThingYoullFind#4]
Some people rather report as spam as it, people can just make "Hey install this awesome mod that overyhaul verything @#!#!@#1

**Comment by JoostMSoftware** [comment]
Good morning! 

 I totally understand what you mean, but like  I told in the comments on CF, I will provide the pictures as soon possible as there is not a lot of content to be displayed at the moment (I'm working out on a idea to change that). Tho, what's wrong with the current description? As my mod doesn't overhaul EVERYTHING, it just adds more content based around exploration, mob killing and more. 

It's a simple concept I haven't seen used a lot for these kinds of mods.

**Comment by JoostMSoftware** [comment]
closed due no response
